/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'bq-base': '#020617',
        'bq-surface': '#0f172a',
        'bq-card': '#1e293b',
        'bq-border': '#334155',
        'bq-accent': '#a855f7',
        'bq-accent2': '#ec4899',
        'bq-gold': '#f59e0b',
        'bq-green': '#22c55e',
        'bq-blue': '#3b82f6',
        'bq-text': '#e2e8f0',
        'bq-muted': '#94a3b8',
      },
      fontFamily: {
        sans: ['"Inter"', '"Segoe UI"', 'system-ui', 'sans-serif'],
        display: ['"Space Grotesk"', '"Inter"', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"Fira Code"', 'monospace'],
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      animation: {
        'float-slow': 'floatSlow 8s ease-in-out infinite',
        'float-medium': 'floatMedium 6s ease-in-out infinite',
        'float-fast': 'floatFast 4s ease-in-out infinite',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
        'shimmer': 'shimmer 2.5s linear infinite',
        'streak-pulse': 'streakPulse 1.5s ease-in-out infinite',
        'score-tick': 'scoreTick 0.4s ease-out',
        'slide-up': 'slideUp 0.5s cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-down': 'slideDown 0.4s cubic-bezier(0.16, 1, 0.3, 1)',
        'scale-in': 'scaleIn 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
        'fade-in': 'fadeIn 0.4s ease-out',
      },
      keyframes: {
        floatSlow: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)', opacity: '0.3' },
          '50%': { transform: 'translateY(-30px) rotate(5deg)', opacity: '0.6' },
        },
        floatMedium: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)', opacity: '0.2' },
          '50%': { transform: 'translateY(-20px) rotate(-3deg)', opacity: '0.5' },
        },
        floatFast: {
          '0%, 100%': { transform: 'translateY(0px)', opacity: '0.15' },
          '50%': { transform: 'translateY(-15px)', opacity: '0.4' },
        },
        pulseGlow: {
          '0%, 100%': { opacity: '0.4', transform: 'scale(1)' },
          '50%': { opacity: '0.8', transform: 'scale(1.05)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% center' },
          '100%': { backgroundPosition: '200% center' },
        },
        streakPulse: {
          '0%, 100%': { transform: 'scale(1)', filter: 'drop-shadow(0 0 4px #f97316)' },
          '50%': { transform: 'scale(1.15)', filter: 'drop-shadow(0 0 10px #f97316)' },
        },
        scoreTick: {
          '0%': { transform: 'scale(0.8)', opacity: '0' },
          '60%': { transform: 'scale(1.1)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      boxShadow: {
        'glow-purple': '0 0 20px rgba(168, 85, 247, 0.4)',
        'glow-pink': '0 0 20px rgba(236, 72, 153, 0.4)',
        'glow-gold': '0 0 20px rgba(245, 158, 11, 0.4)',
        'glow-green': '0 0 20px rgba(34, 197, 94, 0.4)',
        'inner-glow': 'inset 0 0 20px rgba(168, 85, 247, 0.1)',
      },
    },
  },
  safelist: [
    // Dynamic bg- classes generated by FeedbackModal's colorClass.replace('text-','bg-')
    'bg-bq-green',
    'bg-bq-gold',
    'bg-bq-blue',
    'bg-red-400',
    // Dynamic animation delays used in BackgroundEffects
    'animate-pulse-glow',
    'animate-float-slow',
    'animate-float-medium',
    'animate-float-fast',
    'animate-score-tick',
    'animate-scale-in',
    'animate-slide-up',
    'animate-fade-in',
    'animate-streak-pulse',
    'animate-shimmer',
  ],
  plugins: [],
};
